export const ICON_MAP = {
  Inicio: "home",
  Perfil: "user",
  Categorias: "list",
  Favoritos: "heart",
  Delete: "trash",
  Search: "search",
  Cart: "shopping-cart",
  Passoword: "lock",
  Visible: "eye",
  Invisible: "eye-off",
  Wallet: "credit-card",
  Truck: "truck",
  Package: "package",
  TrendingUp: "trending-up",
  Widgets: "grid",
  Edit: "edit-2",
  Save: "save",
  Add: "plus",
  Arrow_Right: "chevron-right",
};
